package com.example.model

import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

enum class AppLanguage(val code: String, val displayName: String, val flagEmoji: String) {
    FRENCH("fr", "Français", "🇫🇷"),
    ENGLISH("en", "English", "🇬🇧"),
    HAUSA("ha", "Hausa", "🇳🇬")
}

object LocalizationManager {
    private val _currentLanguage = MutableStateFlow(AppLanguage.FRENCH)
    val currentLanguage: StateFlow<AppLanguage> = _currentLanguage.asStateFlow()

    fun setLanguage(language: AppLanguage) {
        _currentLanguage.value = language
    }

    private val translations: Map<AppLanguage, Map<String, String>> = mapOf(
        AppLanguage.FRENCH to mapOf(
            "app_title" to "Prends & Rends",
            "app_subtitle" to "Suivi des prêts & emprunts",
            "cloud_syncing" to "Sync...",
            "cloud_synced" to "Cloud actif",
            "search_placeholder" to "Rechercher objet, personne, ville...",
            "tab_all" to "Tous",
            "tab_lent" to "Je prête",
            "tab_borrowed" to "J'emprunte",
            "tab_overdue" to "En retard",
            "tab_returned" to "Rendus",
            "kpi_lent" to "Prêtés",
            "kpi_borrowed" to "Empruntés",
            "kpi_overdue" to "En retard",
            "kpi_returned" to "Rendus",
            "cat_all" to "Toutes",
            "cat_tools" to "Outils",
            "cat_books" to "Livres",
            "cat_high_tech" to "High-Tech",
            "cat_money" to "Argent",
            "cat_games" to "Jeux",
            "cat_clothes" to "Vêtements",
            "cat_other" to "Autre",
            "lent_to" to "Prêté à",
            "borrowed_from" to "Emprunté à",
            "overdue_badge" to "En retard !",
            "due_on" to "À rendre pour le",
            "no_deadline" to "Sans date limite",
            "mark_returned" to "Marquer rendu ✓",
            "mark_active" to "Remettre en cours",
            "share_reminder" to "Rappel",
            "delete" to "Supprimer",
            "new_loan" to "Nouveau",
            "sheet_title" to "Nouveau prêt / emprunt",
            "operation_type" to "Type d'opération",
            "item_title" to "Objet (ex: Perceuse, Livre, 50€)",
            "person_name_lent" to "Prêté à qui ? (ex: Thomas Dubois)",
            "person_name_borrowed" to "Emprunté à qui ? (ex: Sophie Martin)",
            "category" to "Catégorie",
            "due_date_delay" to "Délai de retour",
            "delay_7_days" to "Dans 7 jours",
            "delay_14_days" to "Dans 14 jours",
            "delay_30_days" to "Dans 1 mois",
            "delay_none" to "Sans date limite",
            "notes_placeholder" to "Remarques / État de l'objet (accessoires, caution...)",
            "cancel" to "Annuler",
            "save" to "Enregistrer",
            "satellite_tracking" to "Position satellite GPS",
            "capture_gps" to "Capturer position GPS actuelle",
            "capturing_gps" to "Capture GPS en cours...",
            "location_captured" to "Position satellite capturée",
            "open_maps" to "Ouvrir dans Google Maps",
            "open_apple_maps" to "Ouvrir dans Plans (Apple Maps)",
            "voice_note" to "Mémo vocal",
            "record_audio" to "Enregistrer mémo vocal",
            "stop_recording" to "Arrêter l'enregistrement",
            "recording_active" to "Enregistrement en cours...",
            "play_audio" to "Écouter le mémo vocal",
            "pause_audio" to "Pause",
            "delete_audio" to "Supprimer le mémo",
            "media_attachments" to "Photos & Vidéos jointes",
            "add_photo" to "Photo",
            "add_video" to "Vidéo",
            "pick_media" to "Galerie",
            "take_photo" to "Prendre photo",
            "record_video" to "Filmer vidéo",
            "satellite_view" to "Vue Satellite",
            "hybrid_view" to "Mode Hybride",
            "empty_all" to "Vous n'avez aucun prêt ou emprunt enregistré.",
            "empty_lent" to "Vous n'avez prêté aucun objet actuellement.",
            "empty_borrowed" to "Vous n'avez aucun emprunt en cours.",
            "empty_overdue" to "Super ! Aucun prêt ou emprunt en retard.",
            "empty_returned" to "Aucun objet n'a encore été marqué comme rendu.",
            "language" to "Langue",
            "switch_language" to "Changer de langue",
            "reminder_message_template" to "Hello %s ! Petit rappel amical concernant '%s' que je t'ai prêté, à me rendre %s. Merci !"
        ),
        AppLanguage.ENGLISH to mapOf(
            "app_title" to "Give & Take",
            "app_subtitle" to "Loan & Borrow Tracker",
            "cloud_syncing" to "Syncing...",
            "cloud_synced" to "Cloud Active",
            "search_placeholder" to "Search item, borrower, city...",
            "tab_all" to "All",
            "tab_lent" to "Lent",
            "tab_borrowed" to "Borrowed",
            "tab_overdue" to "Overdue",
            "tab_returned" to "Settled",
            "kpi_lent" to "Lent",
            "kpi_borrowed" to "Borrowed",
            "kpi_overdue" to "Overdue",
            "kpi_returned" to "Settled",
            "cat_all" to "All",
            "cat_tools" to "Tools",
            "cat_books" to "Books",
            "cat_high_tech" to "High-Tech",
            "cat_money" to "Money",
            "cat_games" to "Games",
            "cat_clothes" to "Clothes",
            "cat_other" to "Other",
            "lent_to" to "Lent to",
            "borrowed_from" to "Borrowed from",
            "overdue_badge" to "Overdue!",
            "due_on" to "Due on",
            "no_deadline" to "No due date",
            "mark_returned" to "Mark Settled ✓",
            "mark_active" to "Mark Active",
            "share_reminder" to "Reminder",
            "delete" to "Delete",
            "new_loan" to "New Loan",
            "sheet_title" to "New Loan / Borrowing",
            "operation_type" to "Operation Type",
            "item_title" to "Item (e.g. Drill, Book, $50)",
            "person_name_lent" to "Lent to whom? (e.g. Thomas)",
            "person_name_borrowed" to "Borrowed from whom? (e.g. Sophie)",
            "category" to "Category",
            "due_date_delay" to "Due delay",
            "delay_7_days" to "In 7 days",
            "delay_14_days" to "In 14 days",
            "delay_30_days" to "In 1 month",
            "delay_none" to "No due date",
            "notes_placeholder" to "Notes / Condition (accessories, caution...)",
            "cancel" to "Cancel",
            "save" to "Save",
            "satellite_tracking" to "GPS Satellite Tracking",
            "capture_gps" to "Capture Current GPS Location",
            "capturing_gps" to "Capturing GPS...",
            "location_captured" to "Satellite position captured",
            "open_maps" to "Open in Google Maps",
            "open_apple_maps" to "Open in Apple Maps",
            "voice_note" to "Voice Note",
            "record_audio" to "Record voice note",
            "stop_recording" to "Stop recording",
            "recording_active" to "Recording audio...",
            "play_audio" to "Play voice note",
            "pause_audio" to "Pause",
            "delete_audio" to "Delete note",
            "media_attachments" to "Attached Photos & Videos",
            "add_photo" to "Photo",
            "add_video" to "Video",
            "pick_media" to "Gallery",
            "take_photo" to "Take Photo",
            "record_video" to "Record Video",
            "satellite_view" to "Satellite View",
            "hybrid_view" to "Hybrid Mode",
            "empty_all" to "You have no loans or borrowings saved.",
            "empty_lent" to "You have not lent any items currently.",
            "empty_borrowed" to "You have no active borrowings.",
            "empty_overdue" to "Great! No overdue items.",
            "empty_returned" to "No items marked as settled yet.",
            "language" to "Language",
            "switch_language" to "Switch language",
            "reminder_message_template" to "Hello %s! Friendly reminder about '%s' I lent you, due on %s. Thanks a lot!"
        ),
        AppLanguage.HAUSA to mapOf(
            "app_title" to "Karɓa & Mayar",
            "app_subtitle" to "Binciken bashi da aro",
            "cloud_syncing" to "Ana sabuntawa...",
            "cloud_synced" to "Cloud yana aiki",
            "search_placeholder" to "Nemo abu, mutum, gari...",
            "tab_all" to "Duka",
            "tab_lent" to "Na bayar bashi",
            "tab_borrowed" to "Na karɓi aro",
            "tab_overdue" to "Ya makara",
            "tab_returned" to "An mayar",
            "kpi_lent" to "Bashi",
            "kpi_borrowed" to "Aro",
            "kpi_overdue" to "Ya makara",
            "kpi_returned" to "An mayar",
            "cat_all" to "Kowane",
            "cat_tools" to "Kayan aiki",
            "cat_books" to "Littattafai",
            "cat_high_tech" to "Kayan zamani",
            "cat_money" to "Kuɗi",
            "cat_games" to "Wasa",
            "cat_clothes" to "Kayan sawa",
            "cat_other" to "Sauran",
            "lent_to" to "An ba wa",
            "borrowed_from" to "An karɓa daga",
            "overdue_badge" to "Lokaci ya wuce!",
            "due_on" to "Ranar mayarwa",
            "no_deadline" to "Babu kayyade lokaci",
            "mark_returned" to "Shaida an mayar ✓",
            "mark_active" to "Koma kan aiki",
            "share_reminder" to "Tunasarwa",
            "delete" to "Goge",
            "new_loan" to "Sabo",
            "sheet_title" to "Sabuwar bayarwa / karɓar aro",
            "operation_type" to "Nau'in ma'amala",
            "item_title" to "Sunan abu (misali: Mashin, Littafi, 5000 NGN)",
            "person_name_lent" to "Wa aka ba wa? (misali: Musa)",
            "person_name_borrowed" to "Daga wa aka karɓa? (misali: Fatima)",
            "category" to "Rukuni",
            "due_date_delay" to "Tsawon lokacin mayarwa",
            "delay_7_days" to "Cikin kwanaki 7",
            "delay_14_days" to "Cikin kwanaki 14",
            "delay_30_days" to "Cikin wata 1",
            "delay_none" to "Babu kayyade lokaci",
            "notes_placeholder" to "Bayanin yanayin kayan (kayan haɗi, jingina...)",
            "cancel" to "Soke",
            "save" to "Ajiye",
            "satellite_tracking" to "Wurin tauraron dan adam (GPS)",
            "capture_gps" to "Ɗauki madaidaicin wurin GPS yanzu",
            "capturing_gps" to "Ana ɗaukar GPS...",
            "location_captured" to "An ɗauki wurin tauraron dan adam",
            "open_maps" to "Buɗe a Google Maps",
            "open_apple_maps" to "Buɗe a Apple Maps",
            "voice_note" to "Muryar tuni",
            "record_audio" to "Yi rikodin murya",
            "stop_recording" to "Tsayar da rikodin",
            "recording_active" to "Ana yin rikodin...",
            "play_audio" to "Saurari muryar",
            "pause_audio" to "Dakata",
            "delete_audio" to "Goge muryar",
            "media_attachments" to "Hotuna & Bidiyoyi",
            "add_photo" to "Hoto",
            "add_video" to "Bidiyo",
            "pick_media" to "Dakin hotuna",
            "take_photo" to "Ɗauki hoto",
            "record_video" to "Ɗauki bidiyo",
            "satellite_view" to "Duba na Tauraro",
            "hybrid_view" to "Yanayin Haɗe",
            "empty_all" to "Baka da wani bashi ko aro da aka ajiye.",
            "empty_lent" to "Baka ba da rancen kowane abu ba a yanzu.",
            "empty_borrowed" to "Baka karɓi aron komai ba a yanzu.",
            "empty_overdue" to "Madalla! Babu wani abu da ya makara.",
            "empty_returned" to "Ba a mayar da wani abu ba tukunna.",
            "language" to "Harshe",
            "switch_language" to "Canza harshe",
            "reminder_message_template" to "Sannu %s! Tunasarwa ce ta abota game da '%s' da na baka aro, wanda za a mayar %s. Nagode sosai!"
        )
    )

    fun string(key: String): String {
        val lang = _currentLanguage.value
        return translations[lang]?.get(key)
            ?: translations[AppLanguage.FRENCH]?.get(key)
            ?: key
    }
}
