import Foundation

public enum AppLanguage: String, CaseIterable, Identifiable {
    case french = "fr"
    case english = "en"
    case hausa = "ha"
    
    public var id: String { rawValue }
    
    public var displayName: String {
        switch self {
        case .french: return "Français"
        case .english: return "English"
        case .hausa: return "Hausa"
        }
    }
    
    public var flagEmoji: String {
        switch self {
        case .french: return "🇫🇷"
        case .english: return "🇬🇧"
        case .hausa: return "🇳🇬"
        }
    }
}

public final class LocalizationManager: ObservableObject {
    public static let shared = LocalizationManager()
    
    @Published public var currentLanguage: AppLanguage = .french
    
    private let translations: [AppLanguage: [String: String]] = [
        .french: [
            "app_title": "Prends & Rends",
            "app_subtitle": "Suivi des prêts & emprunts",
            "cloud_syncing": "Sync...",
            "cloud_synced": "Cloud actif",
            "search_placeholder": "Rechercher objet, personne, ville...",
            "tab_all": "Tous",
            "tab_lent": "Je prête",
            "tab_borrowed": "J'emprunte",
            "tab_overdue": "En retard",
            "tab_returned": "Rendus",
            "kpi_lent": "Prêtés",
            "kpi_borrowed": "Empruntés",
            "kpi_overdue": "En retard",
            "kpi_returned": "Rendus",
            "cat_all": "Toutes",
            "cat_tools": "Outils",
            "cat_books": "Livres",
            "cat_high_tech": "High-Tech",
            "cat_money": "Argent",
            "cat_games": "Jeux",
            "cat_clothes": "Vêtements",
            "cat_other": "Autre",
            "lent_to": "Prêté à",
            "borrowed_from": "Emprunté à",
            "overdue_badge": "En retard !",
            "due_on": "À rendre pour le",
            "no_deadline": "Sans date limite",
            "mark_returned": "Marquer rendu ✓",
            "mark_active": "Remettre en cours",
            "share_reminder": "Rappel",
            "delete": "Supprimer",
            "new_loan": "Nouveau",
            "sheet_title": "Nouveau prêt / emprunt",
            "operation_type": "Type d'opération",
            "item_title": "Nom de l'objet (ex: Perceuse, Livre, 50€)",
            "person_name_lent": "Prêté à qui ? (ex: Thomas)",
            "person_name_borrowed": "Emprunté à qui ? (ex: Sophie)",
            "category": "Catégorie",
            "due_date_delay": "Échéance de retour",
            "delay_7_days": "Dans 7 jours",
            "delay_14_days": "Dans 14 jours",
            "delay_30_days": "Dans 1 mois",
            "delay_none": "Sans date limite",
            "notes_placeholder": "Accessoires inclus, caution, état...",
            "cancel": "Annuler",
            "save": "Enregistrer",
            "satellite_tracking": "Position Satellite GPS",
            "capture_gps": "Capturer position GPS actuelle",
            "capturing_gps": "Capture GPS en cours...",
            "location_captured": "Position satellite capturée",
            "open_maps": "Ouvrir dans Maps",
            "open_apple_maps": "Ouvrir dans Apple Plans",
            "voice_note": "Mémo vocal",
            "record_audio": "Enregistrer mémo vocal",
            "stop_recording": "Arrêter l'enregistrement",
            "recording_active": "Enregistrement en cours...",
            "play_audio": "Écouter le mémo",
            "pause_audio": "Pause",
            "delete_audio": "Supprimer",
            "media_attachments": "Photos & Vidéos jointes",
            "add_photo": "Photo",
            "add_video": "Vidéo",
            "pick_media": "Galerie",
            "satellite_view": "Vue Satellite",
            "hybrid_view": "Mode Hybride",
            "reminder_message_template": "Hello %s ! Petit rappel amical concernant '%s' que je t'ai prêté, à me rendre %s. Merci !"
        ],
        .english: [
            "app_title": "Give & Take",
            "app_subtitle": "Loan & Borrow Tracker",
            "cloud_syncing": "Syncing...",
            "cloud_synced": "Cloud Active",
            "search_placeholder": "Search item, borrower, city...",
            "tab_all": "All",
            "tab_lent": "Lent",
            "tab_borrowed": "Borrowed",
            "tab_overdue": "Overdue",
            "tab_returned": "Settled",
            "kpi_lent": "Lent",
            "kpi_borrowed": "Borrowed",
            "kpi_overdue": "Overdue",
            "kpi_returned": "Settled",
            "cat_all": "All",
            "cat_tools": "Tools",
            "cat_books": "Books",
            "cat_high_tech": "High-Tech",
            "cat_money": "Money",
            "cat_games": "Games",
            "cat_clothes": "Clothes",
            "cat_other": "Other",
            "lent_to": "Lent to",
            "borrowed_from": "Borrowed from",
            "overdue_badge": "Overdue!",
            "due_on": "Due on",
            "no_deadline": "No due date",
            "mark_returned": "Mark Settled ✓",
            "mark_active": "Mark Active",
            "share_reminder": "Reminder",
            "delete": "Delete",
            "new_loan": "New Loan",
            "sheet_title": "New Loan / Borrowing",
            "operation_type": "Operation Type",
            "item_title": "Item name (e.g. Drill, Book, $50)",
            "person_name_lent": "Lent to whom? (e.g. Thomas)",
            "person_name_borrowed": "Borrowed from whom? (e.g. Sophie)",
            "category": "Category",
            "due_date_delay": "Due delay",
            "delay_7_days": "In 7 days",
            "delay_14_days": "In 14 days",
            "delay_30_days": "In 1 month",
            "delay_none": "No due date",
            "notes_placeholder": "Accessories included, deposit, condition...",
            "cancel": "Cancel",
            "save": "Save",
            "satellite_tracking": "GPS Satellite Tracking",
            "capture_gps": "Capture Current GPS Location",
            "capturing_gps": "Capturing GPS...",
            "location_captured": "Satellite position captured",
            "open_maps": "Open in Maps",
            "open_apple_maps": "Open in Apple Maps",
            "voice_note": "Voice Note",
            "record_audio": "Record voice note",
            "stop_recording": "Stop recording",
            "recording_active": "Recording audio...",
            "play_audio": "Play voice note",
            "pause_audio": "Pause",
            "delete_audio": "Delete",
            "media_attachments": "Attached Photos & Videos",
            "add_photo": "Photo",
            "add_video": "Video",
            "pick_media": "Gallery",
            "satellite_view": "Satellite View",
            "hybrid_view": "Hybrid Mode",
            "reminder_message_template": "Hello %s! Friendly reminder about '%s' I lent you, due on %s. Thanks a lot!"
        ],
        .hausa: [
            "app_title": "Karɓa & Mayar",
            "app_subtitle": "Binciken bashi da aro",
            "cloud_syncing": "Ana sabuntawa...",
            "cloud_synced": "Cloud yana aiki",
            "search_placeholder": "Nemo abu, mutum, gari...",
            "tab_all": "Duka",
            "tab_lent": "Na bayar bashi",
            "tab_borrowed": "Na karɓi aro",
            "tab_overdue": "Ya makara",
            "tab_returned": "An mayar",
            "kpi_lent": "Bashi",
            "kpi_borrowed": "Aro",
            "kpi_overdue": "Ya makara",
            "kpi_returned": "An mayar",
            "cat_all": "Kowane",
            "cat_tools": "Kayan aiki",
            "cat_books": "Littattafai",
            "cat_high_tech": "Kayan zamani",
            "cat_money": "Kuɗi",
            "cat_games": "Wasa",
            "cat_clothes": "Kayan sawa",
            "cat_other": "Sauran",
            "lent_to": "An ba wa",
            "borrowed_from": "An karɓa daga",
            "overdue_badge": "Lokaci ya wuce!",
            "due_on": "Ranar mayarwa",
            "no_deadline": "Babu kayyade lokaci",
            "mark_returned": "Shaida an mayar ✓",
            "mark_active": "Koma kan aiki",
            "share_reminder": "Tunasarwa",
            "delete": "Goge",
            "new_loan": "Sabo",
            "sheet_title": "Sabuwar bayarwa / karɓar aro",
            "operation_type": "Nau'in ma'amala",
            "item_title": "Sunan abu (misali: Mashin, Littafi, 5000 NGN)",
            "person_name_lent": "Wa aka ba wa? (misali: Musa)",
            "person_name_borrowed": "Daga wa aka karɓa? (misali: Fatima)",
            "category": "Rukuni",
            "due_date_delay": "Tsawon lokacin mayarwa",
            "delay_7_days": "Cikin kwanaki 7",
            "delay_14_days": "Cikin kwanaki 14",
            "delay_30_days": "Cikin wata 1",
            "delay_none": "Babu kayyade lokaci",
            "notes_placeholder": "Bayanin yanayin kayan (kayan haɗi, jingina...)",
            "cancel": "Soke",
            "save": "Ajiye",
            "satellite_tracking": "Wurin tauraron dan adam (GPS)",
            "capture_gps": "Ɗauki madaidaicin wurin GPS yanzu",
            "capturing_gps": "Ana ɗaukar GPS...",
            "location_captured": "An ɗauki wurin tauraron dan adam",
            "open_maps": "Buɗe a Maps",
            "open_apple_maps": "Buɗe a Apple Plans",
            "voice_note": "Muryar tuni",
            "record_audio": "Yi rikodin murya",
            "stop_recording": "Tsayar da rikodin",
            "recording_active": "Ana yin rikodin...",
            "play_audio": "Saurari muryar",
            "pause_audio": "Dakata",
            "delete_audio": "Goge",
            "media_attachments": "Hotuna & Bidiyoyi",
            "add_photo": "Hoto",
            "add_video": "Bidiyo",
            "pick_media": "Dakin hotuna",
            "satellite_view": "Duba na Tauraro",
            "hybrid_view": "Yanayin Haɗe",
            "reminder_message_template": "Sannu %s! Tunasarwa ce ta abota game da '%s' da na baka aro, wanda za a mayar %s. Nagode sosai!"
        ]
    ]
    
    public func string(_ key: String) -> String {
        return translations[currentLanguage]?[key]
            ?? translations[.french]?[key]
            ?? key
    }
}
